// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxNeXehPdWU035YQbxLejNlapZHeGEGes',
    appId: '1:919039535186:web:38ac17e7916e3bcbd5d78b',
    messagingSenderId: '919039535186',
    projectId: 'device-streaming-feb63d11',
    authDomain: 'device-streaming-feb63d11.firebaseapp.com',
    storageBucket: 'device-streaming-feb63d11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC932jQYMZcweYU0Zu84eAM_rCjTE7OvJE',
    appId: '1:919039535186:android:62685b54d6536407d5d78b',
    messagingSenderId: '919039535186',
    projectId: 'device-streaming-feb63d11',
    storageBucket: 'device-streaming-feb63d11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsQg2W79enBkXY1agevGtDYi_fO_-DCAw',
    appId: '1:919039535186:ios:5f7a640b8a6d3470d5d78b',
    messagingSenderId: '919039535186',
    projectId: 'device-streaming-feb63d11',
    storageBucket: 'device-streaming-feb63d11.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsQg2W79enBkXY1agevGtDYi_fO_-DCAw',
    appId: '1:919039535186:ios:5f7a640b8a6d3470d5d78b',
    messagingSenderId: '919039535186',
    projectId: 'device-streaming-feb63d11',
    storageBucket: 'device-streaming-feb63d11.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxNeXehPdWU035YQbxLejNlapZHeGEGes',
    appId: '1:919039535186:web:16e640cb7bec850ed5d78b',
    messagingSenderId: '919039535186',
    projectId: 'device-streaming-feb63d11',
    authDomain: 'device-streaming-feb63d11.firebaseapp.com',
    storageBucket: 'device-streaming-feb63d11.firebasestorage.app',
  );
}
